config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :medications, only: [:index]
  resources :doctors
  resources :patients

  root 'home#index'

  get 'patients/:id' => 'patients#showinfo', as: :patient_showinfo
  get 'medications/:id' => 'medications#mededit', as: :medication_mededit
  post 'medications/:id' => 'medications#medupdate', as: :medication_medupdate
  get 'medications/:id' => 'medications#meddestroy', as: :medication_meddestroy
  delete 'medications/:id' => 'medications#meddelete', as: :medication_meddelete
  
  resources :hospitals do
    member do
      get :new_doctor
      post :create_doctor
    end
    resources :patients do
      resources :medications do
      end
      collection do
        get :search_names
      end
      member do
        patch :waiting
        patch :doctor
        patch :xray
        patch :surgery
        patch :billpay
        patch :leaving
        get :release
        get :new_doctor
        post :create_doctor
      end
    end
  end
end

  #   end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :medication_patient_joins
  has_many :patients, through: :medication_patient_joins

  validates :name, :presence => {:message => 'Name cannot be blank, form not submitted'}
  validates :description, :presence => {:message => 'Description cannot be blank, form not submitted'}
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_patient, except: [:index, :mededit, :meddelete, :medupdate]
  before_filter :find_hospital, except: [:index, :mededit, :meddelete, :medupdate]
  before_filter :find_medication, only: [:show, :edit, :update, :destroy, :mededit, :meddelete, :medupdate]
  # before_filter :load_medication

  # def load_medication
  #   @medication = Medication.find(params[:medication_id]) if params[:medication_id].present?
  # end

  def index
    @medications = @medication.present? ? @medication.medications : Medication.all
  end

  def new
    @medication = @patient.medications.new
  end

  def create
    @medication = @patient.medications.new medication_params
    success = @medication.save
    if success == true
      flash[:notice] = "Medication was successfully created!"
      redirect_to hospital_patient_path(@hospital, @patient)
    else
      # flash[:error] = "Error detected. Please try again."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @medication.update_attributes medication_params
      redirect_to hospital_patient_path(@hospital, @patient)
  end

  def mededit
  end

  def medupdate
    @medication.update_attributes medication_params
      redirect_to medications_path
  end

  def destroy
    @medication.delete
    redirect_to root_path
  end

  def meddelete
    @medication.delete
    redirect_to medications_path
  end

private
  def find_hospital
    @hospital = Hospital.find params[:hospital_id]
  end

  def find_patient
    @patient = Patient.find params[:patient_id]
  end

  def find_medication
    @medication = Medication.find params[:id]
  end

  def medication_params
    params.require(:medication).permit(:name, :description, :hospital_id)
  end

end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.haml
= bootstrap_form_for @medication, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_field :name, placeholder: "Full name of medication", class: "medication_name"
  %br
  = f.text_field :description, placeholder: "The description of medication", class: "medication_description"
  %br
  = f.form_group do
    = f.submit "Add/Edit Medication", class: "btn btn-success medication_submit"
    = link_to "Cancel", medications_path

app/views/medications/edit.html.haml
%hr
%h4 Edit Medication
= render 'form'

app/views/medications/index.html.haml
%hr
%h1.tac
  %strong Medications
%br
%h5.tac 
  = link_to "Add New Medication(FIX)", root_path
%hr
.media
  .media-body
    %table.table.table-hover
      %thead
        %th Name
        %th Description
        -if current_user.admin?
          %th 
          %th 
      %tbody
      -@medications.each do |medication|
        %tr
          %td 
            = medication.name
          %td 
            = medication.description
          -if current_user.admin?
            %td
              %p
                = link_to 'Edit', medication_mededit_path(medication), :class => 'box'
            %td
              %p
                = link_to 'Delete', medication_meddestroy_path(medication), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'box'

app/views/medications/mededit.html.haml
%hr
%h4 Edit Medication
= bootstrap_form_for :medication, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_field :name, placeholder: "Full name of medication", class: "medication_name"
  %br
  = f.text_field :description, placeholder: "The description of medication", class: "medication_description"
  %br
  = f.form_group do
    = f.submit "Add/Edit Medication", class: "btn btn-success medication_submit"
    = link_to "Cancel", medications_path

app/views/medications/new.html.haml
%hr
%h4 Add Medication
%h6.instruct-message Please enter details in the following fields
= render 'form'

app/views/medications/show.html.haml
%hr
= @medication.name
%br
= @medication.description
%br
= link_to "Return to Hospital Page", hospital_path(@hospital), :class => 'box box-color pull-right'

%hr