config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :medications, only: [:index]
  resources :doctors
  resources :patients

  root 'home#index'

  get 'patients/:id' => 'patients#showinfo', as: :patient_showinfo
  get 'medications/:id' => 'medications#mededit', as: :medication_mededit
  post 'medications/:id' => 'medications#medupdate', as: :medication_medupdate
  get 'medications/:id' => 'medications#meddestroy', as: :medication_meddestroy
  delete 'medications/:id' => 'medications#meddelete', as: :medication_meddelete
  
  resources :hospitals do
    member do
      get :new_doctor
      post :create_doctor
    end
    resources :patients do
      resources :medications do
      end
      collection do
        get :search_names
      end
      member do
        patch :waiting
        patch :doctor
        patch :xray
        patch :surgery
        patch :billpay
        patch :leaving
        get :release
        get :new_doctor
        post :create_doctor
      end
    end
  end
end

  #   end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :hospital_patient_joins
  has_many :hospitals, through: :hospital_patient_joins
  has_many :doctor_hospital_joins
  has_many :doctors, through: :doctor_hospital_joins
  has_many :medication_patient_joins
  has_many :medications, through: :medication_patient_joins

  validates :name, :presence => {:message => 'Name cannot be blank, form not submitted'}
  validates :email, :presence => {:message => 'Email cannot be blank, form not submitted'}
  validates :disorder, :presence => {:message => 'Description cannot be blank, form not submitted'}

  before_create :new_patient_email

  def new_patient_email
    PatientMailer.new_patient_email(self).deliver
  end

  scope :search_names, -> search { where("name like?", "%#{search}%") }

  include Workflow
  workflow do
    state :waiting do
      event :go_to_doctor, transitions_to: :doctor
      event :go_to_xray, transitions_to: :xray
      event :go_to_surgery, transitions_to: :surgery
      event :release, transitions_to: :leaving
    end
    state :doctor do
      event :go_to_xray, transitions_to: :xray
      event :go_to_surgery, transitions_to: :surgery
      event :go_to_billpay, transitions_to: :billpay
    end
    state :xray do
      event :go_to_doctor, transitions_to: :doctor
      event :go_to_surgery, transitions_to: :surgery
      event :go_to_billpay, transitions_to: :billpay
    end
    state :surgery do
      event :go_to_doctor, transitions_to: :doctor
      event :go_to_xray, transitions_to: :xray
      event :go_to_billpay, transitions_to: :billpay
    end
    state :billpay do
      event :release, transitions_to: :leaving
    end       
    state :leaving
  end  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_hospital, only: [:waiting, :doctor, :xray, :surgery, :billpay]
  before_filter :find_patient, only: [:show, :edit, :update, :destroy, :waiting, :doctor, :xray, :surgery, :leaving, :billpay, :release, :showinfo]

  def index
    @patients = @patient.present? ? @patient.patients : Patient.all
  end

  def show
  end

  def showinfo
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create patient_params
    success = @patient.save
    if success == true
      flash[:notice] = "Patient was successfully created!"
      redirect_to patients_path
    else
      # flash[:error] = "Error detected. Please try again."
      render :new
    end
  end

  def edit
  end

  def update
    success = @patient.update_attributes patient_params
    if success == true
      flash[:notice] = "Successfully updated patient record!"
      redirect_to patients_path
    else
      # flash[:error] = "Please double check your entries"
      render :edit
    end 
  end

  def destroy
    @patient.delete
    redirect_to patients_path
  end

  def waiting
    @patient.go_to_waiting!
    redirect_to hospital_path(@hospital)
  end

  def doctor
    @patient.go_to_doctor!
    respond_to do |format|
      format.js
    end
  end

  def xray
    @patient.go_to_xray!
    respond_to do |format|
      format.js
    end
  end

  def surgery
    @patient.go_to_surgery!
    respond_to do |format|
      format.js
    end
  end

  def billpay
    @patient.go_to_billpay!
    respond_to do |format|
      format.js
    end
  end

  def release
    success = @patient.update_attributes patient_params
    if success == true
      flash[:notice] = "Your patient has been released from the hospital"
      redirect_to root_path
    else
      flash[:error] = "Please enter release notes"
      render :leaving
    end
  end

  def leaving
    @patient.release!
    respond_to do |format|
      format.js
    end
  end

  def search_names
    @search_names = Patient.search_names params[:q]
  end

private
  def patient_params
    params.require(:patient).permit(:name, :email, :disorder, :release_note)
  end
  
  def find_hospital
    @hospital = Hospital.find params[:hospital_id]
  end

  def find_patient
    @patient = Patient.find params[:id]
  end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
= bootstrap_form_for [@hospital, @patient], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_field :name, placeholder: "Full name of patient", class: "patient_name"
  %br
  = f.email_field :email, placeholder: "The email of patient", class: "patient_email"
  %br
  = f.text_field :disorder, placeholder: "The disorder of patient", class: "patient_disorder"
  %br
  = f.form_group do
    = f.submit "Add/Edit Patient", class: "btn btn-success patient_submit"
    = link_to "Cancel", patients_path

  / %br
  / = f.label :doctor
  / = f.text_field :doctor, class: "patient_doctor"
  / %br
  / - @hospitals.each do |hospital|
  /   = check_box_tag 'patient[hospital_ids][]', hospital.id, @patient.hospitals.include?(hospital), {id: "hospital_id_#{hospital.id}"}
  /   = label_tag "hospital_id_#{hospital.id}", hospital.name
  / %br

app/views/patients/_search.html.haml
= form_tag search_names_hospital_patients_path(@hospital, @patient, anchor: "search-details"), method: :get, class: 'patient_search' do
  = text_field_tag "q", "", placeholder: "Search"
  = submit_tag "Search"

app/views/patients/billpay.js.erb
console.log("<%= @patient.inspect %>")
$("tr.patient_" + "<%= @patient.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'hospitals/table_with_workflow', locals: { patient: @patient})) %>"
)

app/views/patients/doctor.js.erb
console.log("<%= @patient.inspect %>")
$("tr.patient_" + "<%= @patient.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'hospitals/table_with_workflow', locals: { patient: @patient})) %>"
)

app/views/patients/edit.html.haml
%hr
%h3 Edit Patient Information
=render 'form'

app/views/patients/index.html.haml
%hr
%h1.tac
  %strong Patients
%br
%h5.tac 
  = link_to "Add New Patient", new_patient_path
%hr
.media
  .media-body
    %table.table.table-hover
      %thead
        %th Name
        %th Disorder
        -if current_user.admin?
          %th 
          %th 
      %tbody
      - @patients.each do |patient|
        %tr
          %td= link_to patient.name, patient_showinfo_path(patient)
          %td= patient.disorder
          -if current_user.admin?
            %td
              %p
                / = link_to 'Edit', edit_patient_path, :class => 'box'
                = link_to 'Edit', root_path, :class => 'box'
            %td
              %p
                = link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'box'

app/views/patients/leaving.html.haml
%hr
%h3 Release Form

%h4 Add any notes for the release of patient

%span.label.label-danger
  Patient's Name: 
= @patient.name
%p
%span.label.label-danger
  Symptoms: 
= @patient.description
%p

.well.bs-component
  = form_for [@hospital, @patient], :html => {:class => "form-horizontal"} do |f|
    %fieldset
      .form-group
        = f.label :release_note, class: "col-lg-2 control-label"
        .col-lg-10
          = f.text_area :release_note, class: "form-control"
      .form-group
        = f.submit 'Submit', :class => 'pull-right'

= link_to "Home", root_path, :class => 'box box-color pull-right'

app/views/patients/leaving.js.haml
// erb code
// console.log("<%= @patient.inspect %>")
// $("tr.patient_" + "<%= @patient.id %>").remove();

// haml code
console.log("#{@patient.inspect}")
$("tr.patient_#{ @patient.id }").remove()
$("div.patients_released").append(
"#{@patient.name} helped at #{ @patient.updated_at.strftime('%l:%M%p') }<br>"
);

app/views/patients/new.html.haml
%hr
%h4 Add New Patient
%h6.instruct-message Please enter details in the following fields
=render 'form'

app/views/patients/search_names.html.haml
%hr
%a{ class: 'search-details', name: 'search-details'}
%h4 Search Results
%p

%ul
  - @search_names.each do |patient|
    %li
      = patient.name

= link_to "Return to Hospital Page", hospital_path(@hospital), :class => 'box box-color pull-right'

app/views/patients/show.html.haml
%hr
%a{ class: 'patient-details', name: 'patient-details'}
%br

.row
  .col-md-offset-1.col-md-10.col-lg-offset-2.col-lg-8
    .well.profile
      .col-sm-12
        .col-xs-12.col-sm-8
          %h2 
            = @patient.name
          %br
          %p
            %strong Disorder:
            %ul
              %li
                = @patient.disorder
          %p
            %strong Release Notes:
            %ul
              %li
                = @patient.release_note
          %p
            %strong Patient at:
            %br
          - @patient.hospitals.each do |hospital|
            %ul
              %li
                = hospital.name
                %br
                = hospital.location
                %p
          %p
            %strong Medication List:
          - @patient.medications.each do |medication|
            %ul
              %li
                = medication.name
                %br
                = medication.description
                %p
          %p
        .col-xs-12.col-sm-4.text-center
          %figure
            %img.img-circle.img-responsive{:alt => "", :src => "/assets/profile-head.png"}
            %br
            %strong Workflow Status
            = @patient.workflow_state
            %p
            -if current_user.admin?
              = link_to "Edit Patient", edit_patient_path(@patient), :class => 'box'

app/views/patients/showinfo.html.haml
%hr
%a{ class: 'patient-details', name: 'patient-details'}
%p

.tac
  %h2 
    %strong Patient Information
%br

.row
  .col-md-offset-1.col-md-10.col-lg-offset-2.col-lg-8
    .well.profile
      .col-sm-12
        .col-xs-12.col-sm-8
          %h3
            = @patient.name
          %br
          %p
            %strong Disorder:
            %ul
              %li
                = @patient.disorder
          %p
            %strong Release Notes:
            %ul
              %li
                = @patient.release_note
          %p
            %strong Patient at:
            %br
          - @patient.hospitals.each do |hospital|
            %ul
              %li
                = hospital.name
                %br
                = hospital.location
                %p
          %p
            %strong Medication List:
          - @patient.medications.each do |medication|
            %ul
              %li
                = medication.name
                %br
                = medication.description
                %p
          %p
        .col-xs-12.col-sm-4.text-center
          %figure
            %img.img-circle.img-responsive{:alt => "", :src => "/assets/profile-head.png"}
            %br
            %strong Workflow Status
            = @patient.workflow_state

app/views/patients/surgery.js.erb
console.log("<%= @patient.inspect %>")
$("tr.patient_" + "<%= @patient.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'hospitals/table_with_workflow', locals: { patient: @patient})) %>"
)

app/views/patients/xray.js.erb
console.log("<%= @patient.inspect %>")
$("tr.patient_" + "<%= @patient.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'hospitals/table_with_workflow', locals: { patient: @patient})) %>"
)