config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :medications, only: [:index]
  resources :doctors
  resources :patients

  root 'home#index'

  get 'patients/:id' => 'patients#showinfo', as: :patient_showinfo
  get 'medications/:id' => 'medications#mededit', as: :medication_mededit
  post 'medications/:id' => 'medications#medupdate', as: :medication_medupdate
  get 'medications/:id' => 'medications#meddestroy', as: :medication_meddestroy
  delete 'medications/:id' => 'medications#meddelete', as: :medication_meddelete
  
  resources :hospitals do
    member do
      get :new_doctor
      post :create_doctor
    end
    resources :patients do
      resources :medications do
      end
      collection do
        get :search_names
      end
      member do
        patch :waiting
        patch :doctor
        patch :xray
        patch :surgery
        patch :billpay
        patch :leaving
        get :release
        get :new_doctor
        post :create_doctor
      end
    end
  end
end

  #   end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :hospital_patient_joins
  has_many :patients, through: :hospital_patient_joins
  has_many :doctor_hospital_joins
  has_many :doctors, through: :doctor_hospital_joins

  validates :name, :presence => {:message => 'Name cannot be blank, form not submitted'}
  validates :location, :presence => {:message => 'Location cannot be blank, form not submitted'}
  validates :specialty, :presence => {:message => 'Specialty cannot be blank, form not submitted'}

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_hospital, only: [:show, :edit, :update, :destroy, :new_doctor, :create_doctor]

  def index
    @hospitals = @hospital.present? ? @hospital.hospitals : Hospital.all
  end

  def show
    @patients_processing = @hospital.patients.where.not(workflow_state: 'leaving')
    @patients_completed = @hospital.patients.where(workflow_state: 'leaving')
    @patients = Patient.order("id").page(params[:page]).per(3)
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.create hospital_params
    success = @hospital.save
    if success == true
      flash[:notice] = "Hospital was successfully created!"
      redirect_to hospitals_path
    else
      # flash[:error] = "Error detected. Please try again."
      render :new
    end
  end

  def edit
  end

  def update
    success = @hospital.update_attributes hospital_params
    if success == true
      flash[:notice] = "Successfully updated hospital record!"
      redirect_to hospitals_path
    else
      # flash[:error] = "Please double check your entries"
      render :edit
    end 
  end

  def destroy
    @hospital.delete
    redirect_to hospitals_path
  end

  def new_doctor
    @doctor = @hospital.doctors.new
  end

  def create_doctor 
    @doctor = @hospital.doctors.create doctor_params
    success = @doctor.save
    if success == true
      flash[:notice] = "Doctor was successfully created!"
      redirect_to hospital_path(@hospital)
    else
      # flash[:error] = "Error detected. Please try again."
      render :new_doctor
    end
  end

private
  def find_hospital
    @hospital = Hospital.find params[:id]
  end

  def hospital_params
    params.require(:hospital).permit(:name, :location, :specialty)
  end

  def doctor_params
      params.require(:doctor).permit(:name, :specialty)
  end

end

app/helpers/hospitals_helper.rb
module HospitalsHelper
  def workflow_links(patient)
    if patient.workflow_state == 'waiting'
      a = link_to "Doctor", 'javascript:void(0)', class: "box patient_#{patient.id} doctor change_workflow", workflow_url: doctor_hospital_patient_path(@hospital, patient)
      a += link_to "Xray", 'javascript:void(0)', class: "box patient_#{patient.id} xray change_workflow", workflow_url: xray_hospital_patient_path(@hospital, patient)
      a += link_to "Surgery", 'javascript:void(0)', class: "box patient_#{patient.id} surgery change_workflow", workflow_url: surgery_hospital_patient_path(@hospital, patient)
      a += link_to "Leaving", 'javascript:void(0)', class: "box patient_#{patient.id} leaving change_workflow", workflow_url: leaving_hospital_patient_path(@hospital, patient)
    elsif patient.workflow_state == 'doctor'
      b = link_to "Xray", 'javascript:void(0)', class: "box patient_#{patient.id} xray change_workflow", workflow_url: xray_hospital_patient_path(@hospital, patient)
      b += link_to "Surgery", 'javascript:void(0)', class: "box patient_#{patient.id} surgery change_workflow", workflow_url: surgery_hospital_patient_path(@hospital, patient)
      b += link_to "Pay Bill", 'javascript:void(0)', class: "box patient_#{patient.id} billpay change_workflow", workflow_url: billpay_hospital_patient_path(@hospital, patient)
    elsif patient.workflow_state == 'xray'
      c = link_to "Doctor", 'javascript:void(0)', class: "box patient_#{patient.id} doctor change_workflow", workflow_url: doctor_hospital_patient_path(@hospital, patient)
      c += link_to "Surgery", 'javascript:void(0)', class: "box patient_#{patient.id} surgery change_workflow", workflow_url: surgery_hospital_patient_path(@hospital, patient)
      c += link_to "Pay Bill", 'javascript:void(0)', class: "box patient_#{patient.id} billpay change_workflow", workflow_url: billpay_hospital_patient_path(@hospital, patient)
    elsif patient.workflow_state == 'surgery'
      d = link_to "Doctor", 'javascript:void(0)', class: "box patient_#{patient.id} doctor change_workflow", workflow_url: doctor_hospital_patient_path(@hospital, patient)
      d += link_to "Xray", 'javascript:void(0)', class: "box patient_#{patient.id} xray change_workflow", workflow_url: xray_hospital_patient_path(@hospital, patient)
      d += link_to "Pay Bill", 'javascript:void(0)', class: "box patient_#{patient.id} billpay change_workflow", workflow_url: billpay_hospital_patient_path(@hospital, patient)
    elsif patient.workflow_state == 'billpay'
      link_to "Leaving", 'javascript:void(0)', class: "box patient_#{patient.id} leaving change_workflow", workflow_url: leaving_hospital_patient_path(@hospital, patient)
    end
  end
end

app/views/hospitals/_form.html.haml
= bootstrap_form_for @hospital, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_field :name, placeholder: "Full name of hospital", class: "hospital_name"
  %br
  = f.text_field :location, placeholder: "City & state where hospital is located", class: "hospital_location"
  %br
  = f.text_field :specialty, placeholder: "The specialty of hospital", class: "hospital_specialty"
  %br
  = f.check_boxes_collection :doctors, Doctor.all, :id, :name
  %br
  = f.form_group do
    = f.submit "Add/Edit Hospital", class: "btn btn-success hospital_submit"
    = link_to "Cancel", hospitals_path

app/views/hospitals/_table_with_workflow.haml
%tr{ class: "#{patient.workflow_state} patient patient_#{patient.id}"}
  %td
    = link_to patient.name, patient_path(patient), class: "box"
  %td
    (#{patient.workflow_state})
  %td
    = workflow_links(patient)

app/views/hospitals/_workflow.erb
console.log("<%= @patient.inspect %>")
$("tr.patient_" + "<%= @patient.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'hospitals/table_with_workflow', locals: { patient: @patient})) %>"
)

app/views/hospitals/edit.html.haml
%hr
%h4 Edit Hospital
= render 'form'

app/views/hospitals/index.html.haml
%hr
%h1.tac
  %strong Hospitals
%br
%h5.tac 
  = link_to "Add New Hospital", new_hospital_path
%hr
.media
  .media-body
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th Location
          %th Specialty
          -if current_user.admin?
            %th
            %th
      %tbody
        - @hospitals.each do |hospital|
          %tr
            %td= link_to hospital.name, hospital_path(hospital)
            %td= hospital.location
            %td= hospital.specialty
            -if current_user.admin?
              %td
                %p
                  = link_to 'Edit', edit_hospital_path(hospital), :class => 'box'
              %td
                %p
                  = link_to 'Delete', hospital, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'box'
                

app/views/hospitals/new.html.haml
%hr
%h4 New Hospital
= render 'form'

app/views/hospitals/new_doctor.html.haml
%hr
%h4 Add New Doctor
%h6.instruct-message Please enter details in the following fields
= form_for [@hospital, @doctor], url: create_doctor_hospital_path(@hospital) do |f|
  = f.label :name
  = f.text_field :name, class: "doctor_name"
  = f.label :specialty
  = f.text_field :specialty, class: "doctor_specialty"
  %br
  = f.submit "Add/Edit Doctor", class: "doctor_submit"
  
= link_to "Cancel", hospital_path(@hospital)

app/views/hospitals/show.html.haml
%hr
%h1.tac
  = @hospital.name
%br
%h2.tac 
  %strong
  = @hospital.location
%h5.tac
  %br
  Specialty: 
  = @hospital.specialty
%hr
= link_to "New patient", new_hospital_patient_path(@hospital, anchor: "patient-details"), :class => 'box box-color pull-right'

= render 'patients/search'

%h4 Below are the list of patients currently waiting

.list
  %table.table-hover
    %tbody
      %tr
        %th Name
        %th Status
        %th Action
      - @patients_processing.each do |patient|
        = render "table_with_workflow", patient: patient

%hr

%h4 Below are the list of patients who have been helped at this hospital

.patients_released
  - @patients_completed.each do |patient|
    = link_to patient.name, hospital_patient_path(@hospital, patient)
    helped at
    = patient.updated_at.strftime("%l:%M%p")
    %br

%hr

= link_to "New Doctor", new_doctor_hospital_path(@hospital), :class => 'box box-color pull-right'

%h4 Below are the list of doctors practicing at this hosptial

%p
- @hospital.doctors.each do |doctor|
  = doctor.name
  %br

%hr