config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :medications, only: [:index]
  resources :doctors
  resources :patients

  root 'home#index'

  get 'patients/:id' => 'patients#showinfo', as: :patient_showinfo
  get 'medications/:id' => 'medications#mededit', as: :medication_mededit
  post 'medications/:id' => 'medications#medupdate', as: :medication_medupdate
  get 'medications/:id' => 'medications#meddestroy', as: :medication_meddestroy
  delete 'medications/:id' => 'medications#meddelete', as: :medication_meddelete
  
  resources :hospitals do
    member do
      get :new_doctor
      post :create_doctor
    end
    resources :patients do
      resources :medications do
      end
      collection do
        get :search_names
      end
      member do
        patch :waiting
        patch :doctor
        patch :xray
        patch :surgery
        patch :billpay
        patch :leaving
        get :release
        get :new_doctor
        post :create_doctor
      end
    end
  end
end

  #   end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # belongs_to :curable, polymorphic: true
  has_many :doctor_patient_joins
  has_many :patients, through: :doctor_patient_joins
  has_many :doctor_hospital_joins
  has_many :hospitals, through: :doctor_hospital_joins

  validates :name, :presence => {:message => 'Name cannot be blank, form not submitted'}
  validates :specialty, :presence => {:message => 'Specialty cannot be blank, form not submitted'}
  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  # before_filter :find_hospital, except: :index
  before_filter :find_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = @doctor.present? ? @doctor.doctors : Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.create doctor_params
    success = @doctor.save
    if success == true
      flash[:notice] = "Doctor was successfully created!"
      redirect_to doctors_path
    else
      # flash[:error] = "Error detected. Please try again."
      render :new
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    success = @doctor.update_attributes doctor_params
    if success == true
      flash[:notice] = "Successfully updated doctor record!"
      redirect_to doctors_path
    else
      # flash[:error] = "Please double check your entries"
      render :edit
    end 
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.delete
    redirect_to doctors_path
  end

private
  def find_hospital
    @hospital = Hospital.find params[:hospital_id]
  end

  def find_doctor
    @doctor = Doctor.find(params[:doctor_id]) if params[:doctor_id].present?
  end

  def doctor_params
    params.require(:doctor).permit(:name, :specialty)
  end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
= bootstrap_form_for @doctor, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_field :name, placeholder: "Full name of doctor", class: "doctor_name"
  %br
  = f.text_field :specialty, placeholder: "The specialty of doctor", class: "doctor_specialty"
  %br
  = f.check_boxes_collection :hospitals, Hospital.all, :id, :name
  %br
  = f.form_group do
    = f.submit "Add/Edit doctor", class: "btn btn-success doctor_submit"
    = link_to "Cancel", doctors_path

app/views/doctors/edit.html.haml
%hr
%h4 Edit Doctor
= render 'form'

app/views/doctors/index.html.haml
%hr
%h1.tac
  %strong Doctors
%br
%h5.tac 
  = link_to "Add New Doctor", new_doctor_path
%hr
.media
  .media-body
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th Specialty
          -if current_user.admin?
            %th
            %th
      %tbody
        - @doctors.each do |doctor|
          %tr
            %td= link_to doctor.name, doctor_path(doctor)
            %td= doctor.specialty
            -if current_user.admin?
              %td
                %p
                  = link_to 'Edit', edit_doctor_path(doctor), :class => 'box'
              %td
                %p
                  = link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'box'

app/views/doctors/new.html.haml
%hr
%h4 New Doctor
= render 'form'

app/views/doctors/show.html.haml
%hr
%a{ class: 'doctor-details', name: 'doctor-details'}
%p

.tac
  %h2 
    %strong Doctor Information
%br

.row
  .col-md-offset-1.col-md-10.col-lg-offset-2.col-lg-8
    .well.profile
      .col-sm-12
        .col-xs-12.col-sm-8
          %h3
            = @doctor.name
            %p
          Specialty:
          %strong
            = @doctor.specialty
          %p
        .col-xs-12.col-sm-4.text-center
          %figure
            %img.img-circle.img-responsive{:alt => "", :src => "/assets/profile-head.png"}